//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikipediaAutomation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WikipediaAutomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while searching: Search request is longer than the maximum allowed length. (314 &gt; 300).
        /// </summary>
        internal static string ErrorMsgExceedsLengthLimit {
            get {
                return ResourceManager.GetString("ErrorMsgExceedsLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        internal static string HomeLanguageChinese {
            get {
                return ResourceManager.GetString("HomeLanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string HomeLanguageEnglish {
            get {
                return ResourceManager.GetString("HomeLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string HomeLanguageFrench {
            get {
                return ResourceManager.GetString("HomeLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string HomeLanguageGerman {
            get {
                return ResourceManager.GetString("HomeLanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string HomeLanguageItalian {
            get {
                return ResourceManager.GetString("HomeLanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string HomeLanguageJapanese {
            get {
                return ResourceManager.GetString("HomeLanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        internal static string HomeLanguagePolish {
            get {
                return ResourceManager.GetString("HomeLanguagePolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string HomeLanguagePortuguese {
            get {
                return ResourceManager.GetString("HomeLanguagePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string HomeLanguageRussian {
            get {
                return ResourceManager.GetString("HomeLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string HomeLanguageSpanish {
            get {
                return ResourceManager.GetString("HomeLanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zh.wikipedia.org.
        /// </summary>
        internal static string HomePageURLChinese {
            get {
                return ResourceManager.GetString("HomePageURLChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org.
        /// </summary>
        internal static string HomePageURLEnglish {
            get {
                return ResourceManager.GetString("HomePageURLEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fr.wikipedia.org.
        /// </summary>
        internal static string HomePageURLFrench {
            get {
                return ResourceManager.GetString("HomePageURLFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://de.wikipedia.org.
        /// </summary>
        internal static string HomePageURLGerman {
            get {
                return ResourceManager.GetString("HomePageURLGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://it.wikipedia.org.
        /// </summary>
        internal static string HomePageURLItalian {
            get {
                return ResourceManager.GetString("HomePageURLItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ja.wikipedia.org.
        /// </summary>
        internal static string HomePageURLJapanese {
            get {
                return ResourceManager.GetString("HomePageURLJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pl.wikipedia.org.
        /// </summary>
        internal static string HomePageURLPolish {
            get {
                return ResourceManager.GetString("HomePageURLPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pt.wikipedia.org.
        /// </summary>
        internal static string HomePageURLPortuguese {
            get {
                return ResourceManager.GetString("HomePageURLPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ru.wikipedia.org.
        /// </summary>
        internal static string HomePageURLRussian {
            get {
                return ResourceManager.GetString("HomePageURLRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://es.wikipedia.org.
        /// </summary>
        internal static string HomePageURLSpanish {
            get {
                return ResourceManager.GetString("HomePageURLSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request-URI Too Long.
        /// </summary>
        internal static string HomeSearchFailureText {
            get {
                return ResourceManager.GetString("HomeSearchFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracket.
        /// </summary>
        internal static string HomeSearchLeftCurlyBracketResult {
            get {
                return ResourceManager.GetString("HomeSearchLeftCurlyBracketResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parenthesis.
        /// </summary>
        internal static string HomeSearchRedirectTerm {
            get {
                return ResourceManager.GetString("HomeSearchRedirectTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Redirected from Parenthesis).
        /// </summary>
        internal static string HomeSearchRedirectText {
            get {
                return ResourceManager.GetString("HomeSearchRedirectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz.
        /// </summary>
        internal static string HomeSearchTermExceedsLengthLimit {
            get {
                return ResourceManager.GetString("HomeSearchTermExceedsLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        internal static string HomeSearchTermLeftCurlyBracket {
            get {
                return ResourceManager.GetString("HomeSearchTermLeftCurlyBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefgh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeSearchTermOutOfBounds {
            get {
                return ResourceManager.GetString("HomeSearchTermOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium.
        /// </summary>
        internal static string HomeSearchValidTerm {
            get {
                return ResourceManager.GetString("HomeSearchValidTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/Selenium.
        /// </summary>
        internal static string HomeSearchValidTermURL {
            get {
                return ResourceManager.GetString("HomeSearchValidTermURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/Special.
        /// </summary>
        internal static string SpecialPageURL {
            get {
                return ResourceManager.GetString("SpecialPageURL", resourceCulture);
            }
        }
    }
}
