//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikipediaPageObjectModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WikipediaPageObjectModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchInput.
        /// </summary>
        internal static string HomeIDSearchFormTextField {
            get {
                return ResourceManager.GetString("HomeIDSearchFormTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.wikipedia.org/.
        /// </summary>
        internal static string HomePageUrl {
            get {
                return ResourceManager.GetString("HomePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;zh&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoChinese {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;en&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoEnglish {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;fr&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoFrench {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;de&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoGerman {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;it&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoItalian {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;ja&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoJapanese {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;pl&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoPolish {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;pt&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoPortuguese {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;ru&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoRussian {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;es&apos;]/a.
        /// </summary>
        internal static string HomeXPathCentralLogoSpanish {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //body/h1/img[@title=&apos;Wikipedia&apos;].
        /// </summary>
        internal static string HomeXPathCentralLogoTitle {
            get {
                return ResourceManager.GetString("HomeXPathCentralLogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@name=&quot;go&quot;].
        /// </summary>
        internal static string HomeXPathSearchButton {
            get {
                return ResourceManager.GetString("HomeXPathSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h1.
        /// </summary>
        internal static string ResultsXPathSearchFailureHeader {
            get {
                return ResourceManager.GetString("ResultsXPathSearchFailureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;mw-redirectedfrom&apos;].
        /// </summary>
        internal static string ResultsXPathSearchRedirectClass {
            get {
                return ResourceManager.GetString("ResultsXPathSearchRedirectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;mw-search-result-heading&apos;].
        /// </summary>
        internal static string ResultsXPathSearchResultClass {
            get {
                return ResourceManager.GetString("ResultsXPathSearchResultClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;error&apos;].
        /// </summary>
        internal static string ResultsXPathSpecialError {
            get {
                return ResourceManager.GetString("ResultsXPathSpecialError", resourceCulture);
            }
        }
    }
}
