//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainHQPageObjectModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainHQPageObjectModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.brainhq.com/.
        /// </summary>
        internal static string HomePageUrl {
            get {
                return ResourceManager.GetString("HomePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;login-btn&apos;]/tbody/tr/td[&apos;Log in&apos;].
        /// </summary>
        internal static string HomeXPathButtonLogin {
            get {
                return ResourceManager.GetString("HomeXPathButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;lo-topbar-login&apos;].
        /// </summary>
        internal static string HomeXPathLinkLoginDialog {
            get {
                return ResourceManager.GetString("HomeXPathLinkLoginDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;login-in&apos;].
        /// </summary>
        internal static string HomeXPathTextLoginEmailAddress {
            get {
                return ResourceManager.GetString("HomeXPathTextLoginEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;pw-in&apos;].
        /// </summary>
        internal static string HomeXPathTextLoginPassword {
            get {
                return ResourceManager.GetString("HomeXPathTextLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-smry-time&apos;].
        /// </summary>
        internal static string LandingXPathTabAQPerformanceSummaryPage {
            get {
                return ResourceManager.GetString("LandingXPathTabAQPerformanceSummaryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-smry-levs&apos;].
        /// </summary>
        internal static string LandingXPathTabLevelsPerformanceSummaryPage {
            get {
                return ResourceManager.GetString("LandingXPathTabLevelsPerformanceSummaryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-smry-perc&apos;].
        /// </summary>
        internal static string LandingXPathTabPercentilePerformanceSummaryPage {
            get {
                return ResourceManager.GetString("LandingXPathTabPercentilePerformanceSummaryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;nav-prog&apos;].
        /// </summary>
        internal static string LandingXPathTabProgressPage {
            get {
                return ResourceManager.GetString("LandingXPathTabProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-smry-stars&apos;].
        /// </summary>
        internal static string LandingXPathTabStarsPerformanceSummaryPage {
            get {
                return ResourceManager.GetString("LandingXPathTabStarsPerformanceSummaryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;baq-delta&apos;].
        /// </summary>
        internal static string ProgressXPathBrainAQDeltaValues {
            get {
                return ResourceManager.GetString("ProgressXPathBrainAQDeltaValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;baq-val&apos;]/b.
        /// </summary>
        internal static string ProgressXPathBrainAQValue {
            get {
                return ResourceManager.GetString("ProgressXPathBrainAQValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;age-center-num&apos;]/div[@class=&apos;graph-label huge-number&apos;]/br.
        /// </summary>
        internal static string ProgressXPathStaticTextByAgePercentile {
            get {
                return ResourceManager.GetString("ProgressXPathStaticTextByAgePercentile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-det-table&apos;]/tr/td[@class=&apos;td-imp&apos;].
        /// </summary>
        internal static string ProgressXPathStaticTextImprovementValues {
            get {
                return ResourceManager.GetString("ProgressXPathStaticTextImprovementValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-det-table&apos;]/tr/td[@class=&apos;td-meas&apos;].
        /// </summary>
        internal static string ProgressXPathStaticTextLevelValues {
            get {
                return ResourceManager.GetString("ProgressXPathStaticTextLevelValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-det-table&apos;]/tr/td[@class=&apos;td-meas&apos;].
        /// </summary>
        internal static string ProgressXPathStaticTextPercentileValues {
            get {
                return ResourceManager.GetString("ProgressXPathStaticTextPercentileValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-det-table&apos;]/tr/td[@class=&apos;td-meas&apos;].
        /// </summary>
        internal static string ProgressXPathStaticTextStarValues {
            get {
                return ResourceManager.GetString("ProgressXPathStaticTextStarValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;prf-smry-perc&apos;]/div[@class=&apos;big-val&apos;].
        /// </summary>
        internal static string ProgressXPathTabTitleOverallPercentile {
            get {
                return ResourceManager.GetString("ProgressXPathTabTitleOverallPercentile", resourceCulture);
            }
        }
    }
}
